import Head from 'next/head';
import { CommonReactProps } from '../types/common';
import LeftSibar from './LeftSibar';
import RightSidebar from './RightSibar';
import { useRouter } from 'next/router';

function LayoutDefault({ children }: CommonReactProps): JSX.Element {
    return (
        <div className="flex flex-row w-full h-screen">
            <Head>
                <title>IOT-Dashboard</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <LeftSibar />
            <div className="w-10/12">{children}</div>
            <RightSidebar />
        </div>
    );
}
function LayoutUser({ children }: CommonReactProps): JSX.Element {
    return (
        <div className="flex flex-row w-full h-screen">
            <Head>
                <title>IOT-Dashboard</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <LeftSibar />
            <div className="w-full">{children}</div>
        </div>
    );
}

export default function Layout({ children }: CommonReactProps): JSX.Element {
    const router = useRouter();
    return (
        <div>
            {router.pathname === '/User' && <LayoutUser>{children}</LayoutUser>}
            {router.pathname != '/User' && <LayoutDefault>{children}</LayoutDefault>}
        </div>
    );
}
