import Head from 'next/head';
import { CommonReactProps } from '../types/common';
import LeftSibar from './LeftSibar';
import RightSidebar from './RightSibar';
import { useRouter } from 'next/router';
import { ConfigProvider } from 'antd';
import Navbar from './Navbar';

function LayoutDefault({ children }: CommonReactProps): JSX.Element {
    return (
        <div className="flex flex-col w-full h-full bg-slate-800 text-white">
            <Head>
                <title>IOT-Dashboard</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <Navbar />
            </div>
            <div className=" flex flex-row w-full h-screen">
                <LeftSibar />
                <div className="w-full h-screen">{children}</div>
            </div>
        </div>
    );
}
function LayoutUser({ children }: CommonReactProps): JSX.Element {
    return (
        <div className="flex flex-col w-full h-screen bg-slate-800 text-white">
            <Head>
                <title>IOT-Dashboard</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <LeftSibar />
            <div className="w-full">{children}</div>
        </div>
    );
}

export default function Layout({ children }: CommonReactProps): JSX.Element {
    const router = useRouter();
    return (
        <div>
            <ConfigProvider
                theme={{
                    components: {
                        Button: {
                            colorPrimary: '#00b96b',
                            algorithm: true,
                        },
                    },
                }}
            >
                {router.pathname === '/User' && <LayoutUser>{children}</LayoutUser>}
                {router.pathname != '/User' && <LayoutDefault>{children}</LayoutDefault>}
            </ConfigProvider>
        </div>
    );
}
